"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const authMiddleware_1 = require("../middlewares/authMiddleware");
const TaskControllers_1 = require("../controllers/TaskControllers");
const router = (0, express_1.Router)();
router.use(authMiddleware_1.authMiddleware);
router.post("/", TaskControllers_1.TaskController.createTask);
router.get("/:userId", TaskControllers_1.TaskController.getByUser);
router.put('/:id', TaskControllers_1.TaskController.updateTask);
router.delete('/:id', TaskControllers_1.TaskController.deleteTask);
exports.default = router;
